DROP TABLE [dbo].[Болезнь_Граф]
DROP TABLE [dbo].[Заказ_Граф]
DROP TABLE [dbo].[Конкретное лекарство_Граф]
DROP TABLE [dbo].[Лекарство_Граф]
DROP TABLE [dbo].[Продажа_Граф]
DROP TABLE [dbo].[Производитель_Граф]
DROP TABLE [dbo].[Сотрудник_Граф]

DROP TABLE [dbo].[Заказ состоит из_Граф]
DROP TABLE [dbo].[Знает как делать_Граф]
DROP TABLE [dbo].[Продажа состоит из_Граф]
DROP TABLE [dbo].[Лечит_Граф]
DROP TABLE [dbo].[Производит_Граф]
DROP TABLE [dbo].[Сделать заказ_Граф]
DROP TABLE [dbo].[Сделать продажу_Граф]
DROP TABLE [dbo].[Содержит информацию_Граф]